export const GITHUB_CONNECT_REQUEST = "GITHUB_CONNECT_REQUEST";
export const GITHUB_CONNECT_SUCCESS = "GITHUB_CONNECT_SUCCESS";
export const GITHUB_CONNECT_FAILURE = "GITHUB_CONNECT_FAILURE";
export const GITHUB_CONNECT_CLEAR = "GITHUB_CONNECT_CLEAR";