export const GITHUB_CALLBACK_REQUEST = "GITHUB_CALLBACK_REQUEST";
export const GITHUB_CALLBACK_SUCCESS = "GITHUB_CALLBACK_SUCCESS";
export const GITHUB_CALLBACK_FAILURE = "GITHUB_CALLBACK_FAILURE";
export const GITHUB_CALLBACK_CLEAR = "GITHUB_CALLBACK_CLEAR";