export const GITHUB_DISCONNECT_REQUEST = "GITHUB_DISCONNECT_REQUEST";
export const GITHUB_DISCONNECT_SUCCESS = "GITHUB_DISCONNECT_SUCCESS";
export const GITHUB_DISCONNECT_FAILURE = "GITHUB_DISCONNECT_FAILURE";
export const GITHUB_DISCONNECT_CLEAR = "GITHUB_DISCONNECT_CLEAR";