export const GITHUB_SYNC_REQUEST = "GITHUB_SYNC_REQUEST";
export const GITHUB_SYNC_SUCCESS = "GITHUB_SYNC_SUCCESS";
export const GITHUB_SYNC_FAILURE = "GITHUB_SYNC_FAILURE";
export const GITHUB_SYNC_CLEAR = "GITHUB_SYNC_CLEAR";