export const GITHUB_STATUS_REQUEST = "GITHUB_STATUS_REQUEST";
export const GITHUB_STATUS_SUCCESS = "GITHUB_STATUS_SUCCESS";
export const GITHUB_STATUS_FAILURE = "GITHUB_STATUS_FAILURE";
export const GITHUB_STATUS_CLEAR = "GITHUB_STATUS_CLEAR";