export const GITHUB_HISTORY_REQUEST = "GITHUB_HISTORY_REQUEST";
export const GITHUB_HISTORY_SUCCESS = "GITHUB_HISTORY_SUCCESS";
export const GITHUB_HISTORY_FAILURE = "GITHUB_HISTORY_FAILURE";
export const GITHUB_HISTORY_CLEAR = "GITHUB_HISTORY_CLEAR";