export const GITHUB_REPOSITORY_SYNC_REQUEST = "GITHUB_REPOSITORY_SYNC_REQUEST";
export const GITHUB_REPOSITORY_SYNC_SUCCESS = "GITHUB_REPOSITORY_SYNC_SUCCESS";
export const GITHUB_REPOSITORY_SYNC_FAILURE = "GITHUB_REPOSITORY_SYNC_FAILURE";
export const GITHUB_REPOSITORY_SYNC_CLEAR = "GITHUB_REPOSITORY_SYNC_CLEAR";